# Generated by Django 5.0.6 on 2024-05-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormanagementuser',
            name='user_type',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Vendor', 'Vendor'), ('Developer', 'Developer'), ('Admin', 'Admin')], max_length=15, verbose_name='User type'),
        ),
    ]
