# Generated by Django 5.0.6 on 2024-05-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_models', '0002_alter_vendormanagementuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
